services:
  - type: web
    name: abb-product-search
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PORT
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: abb-product-search-db
          property: connectionString
    healthCheckPath: /api/health

databases:
  - name: abb-product-search-db
    databaseName: abb_product_search
    user: abb_user
    plan: free